### ISSUE TITLE
[iOS] Running tests on Github Action

### ISSUE THREAD

**Issue by wcandillon** [FormidableLabs/react-native-owl#124]
Congratulations on this awesome project 🍾🎉

We are considering using it for RN Skia, and we are running into a small issue with having the `xcrun` command available on Github action. This is how the workflow looks like:

```yml
jobs:
  build:
    runs-on: macos-12
    concurrency:
      group: ios-example-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Get Runner Information
        run: /usr/bin/xcodebuild -version # returns Xcode 14.0.1
# build app...
      - uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 14 Pro'
          os_version: '>=16.0'

      - name: e2e Tests
        working-directory: example
        run: yarn e2e:test:ios
```

Returns the following error:

```
$ owl test -p ios
[OWL - CLI] Starting websocket server.
[OWL - CLI] Running tests on ios.
Error: Command failed with ENOENT: xcrun simctl status_bar booted override --time 9:41
spawn xcrun ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16))
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xcrun',
  path: 'xcrun',
  spawnargs: [ 'simctl', 'status_bar', 'booted', 'override', '--time', '9:41' ],
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  originalMessage: 'spawn xcrun ENOENT',
  shortMessage: 'Command failed with ENOENT: xcrun simctl status_bar booted override --time 9:41\n' +
    'spawn xcrun ENOENT',
  command: 'xcrun simctl status_bar booted override --time 9:41',
  escapedCommand: 'xcrun simctl status_bar booted override --time "9:41"',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Do you have any leads on how we could investigate this issue further? Do you plan yourself to run such commands on your own CI?

**Comment by wcandillon** [comment]
When running the owl build command instead of my own build command, I now get the following error:
```
$ owl test -p ios
[OWL - CLI] Starting websocket server.
[OWL - CLI] Running tests on ios.
Error: Command failed with exit code 148: xcrun simctl status_bar iPhone Pro 14 override --time 9:41
    at makeError (/Users/runner/work/react-native-skia/react-native-skia/example/node_modules/react-native-owl/node_modules/execa/lib/error.js:[6](https://github.com/wcandillon/react-native-skia/actions/runs/3242148447/jobs/5315007044#step:16:7)0:11)
    at handlePromise (/Users/runner/work/react-native-skia/react-native-skia/example/node_modules/react-native-owl/node_modules/execa/index.js:11[8](https://github.com/wcandillon/react-native-skia/actions/runs/3242148447/jobs/5315007044#step:16:9):26)
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/wcandillon/react-native-skia/actions/runs/3242148447/jobs/5315007044#step:16:10)6:5) {
  shortMessage: 'Command failed with exit code 148: xcrun simctl status_bar iPhone Pro 14 override --time 9:41',
  command: 'xcrun simctl status_bar iPhone Pro 14 override --time 9:41',
  escapedCommand: 'xcrun simctl status_bar "iPhone Pro [14](https://github.com/wcandillon/react-native-skia/actions/runs/3242148447/jobs/5315007044#step:16:15)" override --time "9:41"',
  exitCode: 148,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Is there a way to get more details about the error? like displaying stderr?

**Comment by taboulot** [comment]
Hi @wcandillon ,

Do not know if it can help but here is my YAML configuration I used (it worked well) :

```yaml
name: Visual Regression - iOS - RN-OWL

on: [workflow_dispatch]

jobs:
  run-visual-regression-ios:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Get Runner Information
        run: /usr/bin/xcodebuild -version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: bundle exec pod install
        working-directory: ./ios

      - uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 13'
          os_version: '>=15.0'

      - name: Run Owl Build
        run: yarn owl:ios:build

      - name: Run Owl Test
        run: yarn owl:ios

      - name: Store screenshots and report as artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: owl-results
          path: ./.owl
```

With react-native-owl 1.1.0

Don't know if it can help 🤷‍♂️
