### ISSUE TITLE
[Android] Running tests on Github Action

### ISSUE THREAD

**Issue by wcandillon** [FormidableLabs/react-native-owl#126]
We are building our app with JDK 11

```yml
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
```

However when trying to run commands like avdmanager, we are getting the following error:
```
$ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_30 --device 'Nexus 5X' --package "system-images;android-30;default;x86_64" --sdcard 512M
Error: Exception in thread "main" java.lang.NoClassDefFoundError: **javax/xml/bind/annotation/XmlSchema**
```

We're not sure how to fix the error; I'm also getting the same error if I try to run the same command on my laptop.
